### ISSUE TITLE
Recent Updates Broke Footsteps Control

### ISSUE THREAD

**Issue by tianevitt** [MarkPearce/footsteps-of-otari-v10#6]
I get the following error when attempting to execute the Open Footsteps Control macro:

init-otari.js:691 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'id')
[Detected 2 packages: footsteps-of-otari, socketlib]
    at Object.openFootstepsController (init-otari.js:691:40)
    at SocketlibSocket._executeLocal (socketlib.js:192:15)
    at SocketlibSocket.executeAsGM (socketlib.js:90:16)
    at Object._openFootstepsController (init-otari.js:112:12)
    at _MacroPF2e.eval (eval at #executeScript (foundry.js:22824:16), <anonymous>:3:47)
    at #executeScript (foundry.js:22828:17)
    at _MacroPF2e.execute (foundry.js:22776:35)
    at MacroConfig._onExecute (foundry.js:75391:17)

This was working in July, so it is something in either the recent Foundry or recent PF2e system updates that broke this.

I tried completely uninstalling and reinstalling, and had the same result. Do you know any mods break this macro?  I have not installed any mods lately.

(I was about to run Level 3 of the Vaults, so this makes me sad. I love this little mod and I hope you can get it working again!)

**Comment by tianevitt** [comment]
Please disregard. The footsteps control worked once I had player actors on the game canvas. Closing as Could Not Duplicate.

**Comment by MarkPearce** [comment]
Ahh that’s interesting though, probably a bug in the multiplayer
implementation. Thanks for mentioning it
