### ISSUE TITLE
V11 Upgrade?

### ISSUE THREAD

**Issue by bogga** [MarkPearce/footsteps-of-otari-v10#7]
Hi, huge fan of the module, my players love to see Otari's little green wisp trek through Gauntlight.
Hoping to upgrade to Foundry 11 and update the pf2e system as a result too.

Is there any chance of this module getting upgraded to v11? I tried it on v11 and got the following error when trying to run the control:
```
caught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
    at Object.openFootstepsController (init-otari.js:691:40)
    at SocketlibSocket._executeLocal (socketlib.js:192:15)
    at SocketlibSocket.executeAsGM (socketlib.js:90:16)
    at Object._openFootstepsController (init-otari.js:112:12)
    at _MacroPF2e.eval (eval at #executeScript (foundry.js:22923:16), <anonymous>:3:47)
    at #executeScript (foundry.js:22927:17)
    at _MacroPF2e.execute (foundry.js:22875:35)
    at MacroConfig._onExecute (foundry.js:75569:17)
o
```

If not I can stick on v10 until we're a few levels deeper :) thanks again for making this module, it really is super handy

**Comment by MarkPearce** [comment]
should work on V11, does on my machine at least.  I've tested 11.314/5.8.2 in electron client, chrome, firefox, and edge.

anything else you can add about your configuration?

**Comment by MarkPearce** [comment]
you have an active scene?

**Comment by bogga** [comment]
Damn, nice remote debugging - I did not have an active scene. Works fine when I activate the proper level!

**Comment by MarkPearce** [comment]
ah cool mb i can add it a warning message for that.
